apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: rudrasankha/todo-app-week-39c3:e0c94e2080de2333f3388ff99eb68d16a779f97e
    ports:
    - containerPort: 80