apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: rudrasankha/todo-app-week-39c3:40f2cfcb6ddc27d0913b53f2d8750757846fb453
    ports:
    - containerPort: 80